import LegalLayout, { type LegalSection } from "@/components/legal/LegalLayout";

const SECTIONS: LegalSection[] = [
  {
    id: "nature",
    title: "Nature of the service",
    content: (
      <>
        <p>
          Cuetronix is a cloud-based <strong>software-as-a-service</strong> (SaaS)
          platform operated by <strong>Cuephoria Tech</strong>. It is delivered
          entirely over the internet as a subscription to the Cuetronix dashboard,
          customer-facing booking portals, APIs, and mobile applications. We do not
          ship any physical goods, hardware, controllers, or consoles as part of a
          subscription to Cuetronix.
        </p>
        <p>
          If you are looking for the service-delivery policy of the{" "}
          <a
            href="https://cuephoria.in"
            target="_blank"
            rel="noopener noreferrer"
          >
            Cuephoria Gaming Lounge
          </a>{" "}
          (our sister venue), please visit cuephoria.in — that policy covers onsite
          gaming sessions and is separate from this SaaS document.
        </p>
      </>
    ),
  },
  {
    id: "provisioning",
    title: "Workspace provisioning timeline",
    content: (
      <>
        <p>
          Cuetronix workspaces are <strong>provisioned instantly</strong> — within a
          few seconds of a successful signup or payment. As soon as the signup flow
          completes, you will receive:
        </p>
        <ul>
          <li>
            a confirmation email at the owner address with a deep link into your new
            workspace (<code>https://&lt;slug&gt;.cuetronix.com</code>);
          </li>
          <li>
            automatic login to the onboarding wizard, where you can import stations,
            upload your menu, and brand the customer portal;
          </li>
          <li>
            an invoice / trial-confirmation, emailed separately to your billing
            contact.
          </li>
        </ul>
        <p>
          In the rare event that provisioning takes longer than 10 minutes — for
          example, because of a downstream outage at a payment gateway or email
          provider — our system will retry automatically and alert{" "}
          <a href="mailto:support@cuetronix.com">support@cuetronix.com</a> so a human
          can step in.
        </p>
      </>
    ),
  },
  {
    id: "onboarding",
    title: "Onboarding & migration",
    content: (
      <>
        <p>
          Starter and Growth plans are <strong>fully self-service</strong> — most
          venues are live within the same day they sign up. For Pro and Enterprise
          plans, Cuephoria Tech provides concierge onboarding that includes:
        </p>
        <ul>
          <li>a 60-minute discovery call to map your stations, pricing and menu;</li>
          <li>
            CSV migration of customers, inventory, and historical booking data from
            your legacy system;
          </li>
          <li>
            sub-domain setup and branding (logo, colours, footer links) on your
            customer portal;
          </li>
          <li>
            staff training over Google Meet, followed by a go-live checklist sent on
            email.
          </li>
        </ul>
        <p>
          Typical Pro onboarding completes within <strong>3&ndash;5 business days</strong>,
          subject to timely data hand-over from your team.
        </p>
      </>
    ),
  },
  {
    id: "digital-delivery",
    title: "Digital receipts, invoices & notifications",
    content: (
      <>
        <p>
          Every transactional artefact generated by Cuetronix is delivered
          electronically:
        </p>
        <ul>
          <li>
            <strong>Subscription invoices</strong> are emailed in PDF form
            immediately after each successful payment.
          </li>
          <li>
            <strong>End-customer receipts</strong> (for bookings and POS sales at
            your venue) are sent instantly over email, SMS, and / or WhatsApp,
            depending on your workspace settings.
          </li>
          <li>
            <strong>Booking confirmations</strong> include a QR code that your staff
            can scan to start the station timer on arrival.
          </li>
          <li>
            <strong>System notifications</strong> (password resets, incident alerts,
            security events) are sent by email in near-real-time.
          </li>
        </ul>
      </>
    ),
  },
  {
    id: "availability",
    title: "Availability & uptime",
    content: (
      <>
        <p>
          Cuetronix targets <strong>99.9% monthly uptime</strong>. Our status and
          incident history are published publicly at{" "}
          <a
            href="https://status.cuetronix.com"
            target="_blank"
            rel="noopener noreferrer"
          >
            status.cuetronix.com
          </a>
          . Scheduled maintenance is announced at least 72 hours in advance, and
          wherever possible performed between 02:00 and 05:00 IST to avoid venue
          peak hours.
        </p>
        <p>
          The Platform is engineered for use during live operations: POS and
          booking flows work offline on a local service worker when the internet
          drops and re-sync automatically when connectivity returns. So your
          Saturday-night cash drawer keeps moving even if your ISP doesn&apos;t.
        </p>
      </>
    ),
  },
  {
    id: "devices",
    title: "Supported devices",
    content: (
      <>
        <p>
          Cuetronix runs in any modern browser (Chrome, Edge, Safari, Firefox — last
          two versions) and as a Progressive Web App on Android and iOS. No
          proprietary hardware is required. For receipt printing we support
          standard ESC/POS thermal printers over USB, Bluetooth, or network. We
          will not, as part of your Cuetronix subscription, ship you a printer,
          tablet, or any other physical hardware.
        </p>
      </>
    ),
  },
  {
    id: "refunds-cancellations",
    title: "Refunds, cancellations & data export",
    content: (
      <>
        <p>
          You can cancel your subscription at any time from{" "}
          <em>Settings &rarr; Billing</em>, and continue using the workspace until
          the end of the current billing cycle. For the full refund rules, please
          see our <a href="/refund-policy">Refund &amp; Cancellation Policy</a>.
        </p>
        <p>
          On request, we will export a complete copy of your Customer Data in
          CSV/JSON format within five business days of a Pro/Enterprise
          cancellation. Self-service exports are always available from the app.
        </p>
      </>
    ),
  },
  {
    id: "changes",
    title: "Changes to this policy",
    content: (
      <>
        <p>
          We may update this Service Delivery Policy from time to time. Material
          changes will be notified by email and by an in-app banner at least 30
          days in advance.
        </p>
      </>
    ),
  },
  {
    id: "contact",
    title: "Contact us",
    content: (
      <>
        <p>For questions about how Cuetronix is delivered:</p>
        <ul>
          <li>
            Support: <a href="mailto:support@cuetronix.com">support@cuetronix.com</a>
          </li>
          <li>
            Billing: <a href="mailto:billing@cuetronix.com">billing@cuetronix.com</a>
          </li>
          <li>
            Postal address: Cuephoria Tech, Tiruchirappalli, Tamil Nadu, India
          </li>
        </ul>
      </>
    ),
  },
];

const ShippingAndDelivery: React.FC = () => {
  return (
    <LegalLayout
      eyebrow="SaaS delivery"
      title="Service Delivery Policy"
      lead={
        <>
          Cuetronix is a pure cloud subscription — provisioned instantly, delivered
          over the internet, and backed by a 99.9% uptime target. No physical
          goods ship. Here&apos;s exactly how your workspace reaches you and how we
          keep it running.
        </>
      }
      lastUpdated="22 April 2026"
      effectiveFrom="22 April 2026"
      sections={SECTIONS}
      contactEmail="support@cuetronix.com"
    />
  );
};

export default ShippingAndDelivery;
